---
- name: Set rsyslog configuration
  copy: src=rsyslog.conf dest=/etc/rsyslog.conf
  notify:
    - restart rsyslog

- name: Copy conf to send logs to remote server
  copy: src=10-send-logs.conf dest=/etc/rsyslog.d
  notify:
    - restart rsyslog

- name: Install Redis
  apt: name=redis-server state=present

- name: Start Redis
  service: name=redis-server state=started

- name: Install Sidekiq
  gem: name=sidekiq state=present user_install=no

- name: Copy Sidekiq config file
  copy: src=sidekiq.yml dest=/config/sidekiq.yml

# For real purposes, you would wrap some stuff in an init.d script so you can manage sidekiq as a service, but let's keep it simple
- name: Start Sidekiq
  shell: bundle exec sidekiq -C /config/sidekiq.yml 2>&1 | logger -t sidekiq

